# Generated by Django 5.1.7 on 2025-03-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id_super_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('type_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.status')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='track.superuser')),
                ('id_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='track.superuser')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback_user', models.AutoField(primary_key=True, serialize=False)),
                ('user_fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('type_feedback', models.CharField(max_length=50)),
                ('id_super_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.superuser')),
            ],
        ),
        migrations.CreateModel(
            name='CourierAnalytics',
            fields=[
                ('id_courier_analytics', models.AutoField(primary_key=True, serialize=False)),
                ('total_orders', models.IntegerField(default=0)),
                ('avg_delivery_time', models.DurationField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id_courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='track.superuser')),
            ],
        ),
    ]
